spring.application.name=EJercicio1
# ===============================
# CONFIGURACIÓN DE BASE DE DATOS H2
# ===============================
spring.datasource.url=jdbc:h2:mem:refugiodb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# create-drop: Borra y recrea las tablas cada que reinicias la app
spring.jpa.hibernate.ddl-auto=create-drop
# Muestra las consultas SQL en la consola (súper útil para depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONSOLA WEB DE H2
# ===============================
# Para entrar usa: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console